model_cfg = dict(
    class_list=('__background__', 'SL', 'HH'),
    rename_class_list={},
    is_multi_gpus=1,
    ANCHOR_SCALES=[1.2, 2.5, 6, 10, 14, 20, 40],
    ANCHOR_RATIOS=[0.333, 0.5, 1.0, 2.0, 3.0],
    POOLING_MODE='align',
    POOLING_SIZE=7,
    FEAT_STRIDE=[8],

    # model="/data/zhangcc/code/detection/pytorch-detecion-deepfashion2/save_models/screen_defect_0721_0100.ckpt",
    model="save_models/screen_defect_0721_0769.ckpt",
    save_model_interval=1,

    MODEL=dict(
        RCNN_CIN=768,
        RPN_CIN=256,
        RCNN_LAST=4096,
        BACKBONE='shortlitehyper',
        DOUT_BASE_MODEL=336,
    ),

    TRAIN=dict(
        dataset="xml",
        train_path="/data0/datasets/mobile_terminal_screen_defect/1/original",
        val_path=None,  # "/data0/datasets/mobile_terminal_screen_defect/1/original",
        # save_dir="/data/zhangcc/code/detection/pytorch-detecion-deepfashion2/save_models/",
        save_dir="save_models/",
        resume_model=None,  # "/data/zhangcc/code/detection/pytorch-detecion-deepfashion2/save_models/screen_defect_0721_0040.ckpt",
        model_name="screen_defect_0721_",
        gpus=(1, 2, 3, ),
        batch_size_per_gpu=48,
        epochs=1000,
        num_works=40,
        LEARNING_RATE=0.00001,
        MOMENTUM=0.9,
        WEIGHT_DECAY=0.0005,
        BATCH_SIZE=128,
        FG_FRACTION=0.25,
        FG_THRESH=0.5,
        BG_THRESH_HI=0.5,
        BG_THRESH_LO=0.0,
        RPN_POSITIVE_OVERLAP=0.7,
        RPN_NEGATIVE_OVERLAP=0.3,
        RPN_FG_FRACTION=0.5,
        RPN_BATCHSIZE=256,
        RPN_NMS_THRESH=0.7,
        RPN_PRE_NMS_TOP_N=12000,
        RPN_POST_NMS_TOP_N=2000,
        RPN_BBOX_INSIDE_WEIGHTS=(1.0, 1.0, 1.0, 1.0),
        TRUNCATED=False,
        BBOX_NORMALIZE_MEANS=(0.0, 0.0, 0.0, 0.0),
        BBOX_NORMALIZE_STDS=(0.1, 0.1, 0.2, 0.2),
        BBOX_INSIDE_WEIGHTS=(1.0, 1.0, 1.0, 1.0),
        RPN_MIN_SIZE=8,
        RPN_CLOBBER_POSITIVES=False,
        RPN_POSITIVE_WEIGHT=-1.0,
        BBOX_NORMALIZE_TARGETS_PRECOMPUTED=True,

    ),

    TEST=dict(
        img_path="/data0/datasets/mobile_terminal_screen_defect/1/original",
        save_dir="/data/zhangcc/data/tmp/test_results/",
        gpus=(0,),
        SCALES=(600,),
        MAX_SIZE=6400,
        TEST_SCALE=512,
        SCALE_MULTIPLE_OF=32,
        iou_thresh=0.5,
        nms_thresh=0.25,
        thresh=0.6,
        small_object_size=0,
        RPN_PRE_NMS_TOP_N=6000,
        RPN_POST_NMS_TOP_N=300,
        RPN_NMS_THRESH=0.7,
        RPN_MIN_SIZE=8,
        gama=False,
    ),
)
