model_cfg = dict(
    class_list=(["__background__", "SL", "HH", "SLQ", "FC",
                 "M", "AJ", "HM", "TT", "QZ", "PP", "LH"]),
    defect_class_list=(["SL", "HH", "SLQ"]),
    rename_class_list={"QZ": ["GG"]},
    confidence_per_cls={'SL': [0.6], 'HH': [0.39], 'SLQ': [0.23], 'FC': [0.56], 'M': [
        0.32], 'AJ': [0.56], 'HM': [0.89], 'TT': [0.82], 'QZ': [0.87], 'PP': [0.58], 'LH': [0.73]},
    ANCHOR_SCALES=[1.0, 2.5, 6, 10, 14, 20, 40],
    ANCHOR_RATIOS=[0.133, 0.333, 0.5, 0.667, 1.0, 1.5, 2.0, 3.0, 7.5],
    POOLING_MODE='align',
    POOLING_SIZE=7,
    FEAT_STRIDE=[8],

    model="save_models/edge_sl_hh_0812_0145.ckpt",
    save_model_interval=1,

    MODEL=dict(
        RCNN_CIN=768,
        RPN_CIN=256,
        RCNN_LAST=4096,
        BACKBONE='shortlitehyper',
        DOUT_BASE_MODEL=336,
    ),

    TRAIN=dict(
        dataset="xml",
        train_path="/data0/datasets/det_edge_defect/4/original",
        val_path=None,
        save_dir="save_models/",
        # resume_model=None,
        resume_model="save_models/edge_sl_hh_0812_0003.ckpt",  # 0807_0145.ckpt
        model_name="edge_sl_hh_0812_",
        gpus=(2, 3, ),
        batch_size_per_gpu=2,
        epochs=1000,
        num_works=8,
        loss_type="smoothL1loss",  # "smoothL1loss" "GIOUloss" "IOUloss"
        LEARNING_RATE=0.0001,
        MOMENTUM=0.9,
        WEIGHT_DECAY=0.0005,
        BATCH_SIZE=128,
        FG_FRACTION=0.25,
        FG_THRESH=0.5,
        BG_THRESH_HI=0.5,
        BG_THRESH_LO=0.0,
        RPN_POSITIVE_OVERLAP=0.7,
        RPN_NEGATIVE_OVERLAP=0.3,
        RPN_FG_FRACTION=0.5,
        RPN_BATCHSIZE=256,
        RPN_NMS_THRESH=0.7,
        RPN_PRE_NMS_TOP_N=12000,
        RPN_POST_NMS_TOP_N=2000,
        RPN_BBOX_INSIDE_WEIGHTS=(1.0, 1.0, 1.0, 1.0),
        TRUNCATED=False,
        BBOX_NORMALIZE_MEANS=(0.0, 0.0, 0.0, 0.0),
        BBOX_NORMALIZE_STDS=(0.1, 0.1, 0.2, 0.2),
        BBOX_INSIDE_WEIGHTS=(1.0, 1.0, 1.0, 1.0),
        RPN_MIN_SIZE=8,
        RPN_CLOBBER_POSITIVES=False,
        RPN_POSITIVE_WEIGHT=-1.0,
        BBOX_NORMALIZE_TARGETS_PRECOMPUTED=True,

    ),

    TEST=dict(
        img_path="/data0/datasets/det_edge_defect/4/original",
        save_dir="/data/zhangcc/data/tmp/test_results/",
        gpus=(1, ),
        SCALES=(600,),
        MAX_SIZE=2880,
        TEST_SCALE=1280,
        SCALE_MULTIPLE_OF=32,
        iou_thresh=0.5,
        nms_thresh=0.25,
        thresh=0.5,
        small_object_size=0,
        RPN_PRE_NMS_TOP_N=6000,
        RPN_POST_NMS_TOP_N=300,
        RPN_NMS_THRESH=0.7,
        RPN_MIN_SIZE=8,
        gama=False,
    ),
)
